julien:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sast_approval
    username: root
    password: Lyx88888888.@
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name: